### ISSUE TITLE
Cambiar nombre

### ISSUE THREAD

**Issue by isthistechsupport** [rubenbuelvas/RonBird#2]
Sugerimos cambiarlo a Flappy Mondá

-Camilo Cortés ft Diego

**Comment by rubenbuelvas** [comment]
Su solicitud ha sido recibida y será evualuada por un comité (donde solo estoy yo) en los próximos días.

**Comment by rubenbuelvas** [comment]
Su solicitud ha sido rechazada.

**Comment by isthistechsupport** [comment]
Quiero sentar mi descontento con la lentitud de estas solicitudes. Y hacerlo en forma de 20 o más issues nuevos todos conteniendo lo mismo.

**Comment by isthistechsupport** [comment]
En realidad 6 issues de los cuales ninguno es relevante. A menos que invente un bot para abrir issues solo. Podría ser Selenium. Hmm... _thinking emoji.jpg_
